<?php
require_once '../../system/system.php';
$head = 'Выдача комплекта';
echo only_reg();
echo admin();
require_once H.'system/head.php';
$sel_users = $pdo->prepare("SELECT `id`, `nick`, `level` FROM `users` WHERE `id` = :all_id");
$sel_users->execute(array(':all_id' => $_GET['id']));
if($sel_users->rowCount() != 0){
$all = $sel_users->fetch(PDO::FETCH_LAZY);
echo'<div class="body_list">';

echo'<div class="info_list">';
echo"<img src='/style/images/user/user.png' alt=''/>Выдача игроку: $all[nick]";
echo'</div>';	
echo'<div class="line_1"></div>';

echo'<div class="menulist">';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=0"><img src="/style/images/body/snarag.png" alt=""/> Комплект Рыцаря</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=6"><img src="/style/images/body/snarag.png" alt=""/> Комплект Защитника</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=16"><img src="/style/images/body/snarag.png" alt=""/> Комплект Ассасина</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=25"><img src="/style/images/body/snarag.png" alt=""/> Комплект Убийцы</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=36"><img src="/style/images/body/snarag.png" alt=""/> Комплект Разрушителя</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=42"><img src="/style/images/body/snarag.png" alt=""/> Комплект Варвара</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=48"><img src="/style/images/body/snarag.png" alt=""/> Комплект Ополченца</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=54"><img src="/style/images/body/snarag.png" alt=""/> Комплект Тьмы</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=60"><img src="/style/images/body/snarag.png" alt=""/> Комплект Короля</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=66"><img src="/style/images/body/snarag.png" alt=""/> Комплект Хранителя</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=72"><img src="/style/images/body/snarag.png" alt=""/> Комплект Правителя</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=78"><img src="/style/images/body/snarag.png" alt=""/> Комплект Тёмного Рыцаря</a></li>';
echo'<div class="line_1"></div>';
echo'<div class="mini-line"></div>';	
echo'<div class="line_1_v"></div>';	
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=84"><img src="/style/images/body/snarag.png" alt=""/> Комплект Знахаря</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=90"><img src="/style/images/body/snarag.png" alt=""/> Комплект Асторема</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=96"><img src="/style/images/body/snarag.png" alt=""/> Комплект Приспешника</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=102"><img src="/style/images/body/snarag.png" alt=""/> Комплект Орвуна</a></li>';
echo'<div class="line_1"></div>';
echo'<div class="mini-line"></div>';	
echo'<div class="line_1_v"></div>';	
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=124"><img src="/style/images/body/snarag.png" alt=""/> Комплект Холода</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=130"><img src="/style/images/body/snarag.png" alt=""/> Комплект Стражника</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=136"><img src="/style/images/body/snarag.png" alt=""/> Комплект Карателя</a></li>';
echo'<div class="line_1"></div>';
echo'<div class="mini-line"></div>';	
echo'<div class="line_1_v"></div>';	
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=142"><img src="/style/images/body/snarag.png" alt=""/> Комплект Паладина</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=148"><img src="/style/images/body/snarag.png" alt=""/> Комплект Следопыта</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=154"><img src="/style/images/body/snarag.png" alt=""/> Комплект Охотника</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=160"><img src="/style/images/body/snarag.png" alt=""/> Комплект Лорда</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/admin_armor_act?act=get&id='.$_GET['id'].'&weapon=163"><img src="/style/images/body/snarag.png" alt=""/> Амулет удачи</a></li>';
echo'<div class="line_1"></div>';
echo'<li><a href="/hero/'.$all['id'].'"><img src="/style/images/body/back.png" alt=""/> Назад</a></li>';
echo'</div>';
echo'</div>';
}else{
echo'<div class="error_list"><img src="/style/images/body/error.png">Игрок не найден!</div>';		
}
require_once H.'system/footer.php';
?>