<?php
echo'<div class="body_list">';
echo'<div class="menulist">';
                                                                    #-ТАБЛИЦЫ ОПЫТА-#

#-Таблица прокачки клана-#
echo'<li><a href="/knowledge_basa?sort=table_exp&spr=exp_clan"><img src="/style/images/user/exp.png" alt=""/> Таблица прокачки клана</a></li>';
if($_GET['spr'] == 'exp_clan'){
echo'<div class="line_1_m"></div>';
echo'<div class="page">';
echo'<div style="padding: 5px;">';
echo'<span class="whit">';
echo'<img src="/style/images/user/level.png">1 ур. - <img src="/style/images/user/exp.png">0<br/>';
echo'<img src="/style/images/user/level.png">2ур. - <img src="/style/images/user/exp.png">10\'000<br/>';
echo'<img src="/style/images/user/level.png">3ур. - <img src="/style/images/user/exp.png">30\'000<br/>';
echo'<img src="/style/images/user/level.png">4ур. - <img src="/style/images/user/exp.png">60\'000<br/>';
echo'<img src="/style/images/user/level.png">5ур. - <img src="/style/images/user/exp.png">100\'000<br/>';
echo'<img src="/style/images/user/level.png">6ур. - <img src="/style/images/user/exp.png">150\'000<br/>';
echo'<img src="/style/images/user/level.png">7ур. - <img src="/style/images/user/exp.png">200\'000<br/>';
echo'<img src="/style/images/user/level.png">8ур. - <img src="/style/images/user/exp.png">250\'000<br/>';
echo'<img src="/style/images/user/level.png">9ур. - <img src="/style/images/user/exp.png">300\'000<br/>';
echo'<img src="/style/images/user/level.png">10ур. - <img src="/style/images/user/exp.png">350\'000<br/>';
echo'<img src="/style/images/user/level.png">11ур. - <img src="/style/images/user/exp.png">400\'000<br/>';
echo'<img src="/style/images/user/level.png">12ур. - <img src="/style/images/user/exp.png">450\'000<br/>';
echo'<img src="/style/images/user/level.png">13ур. - <img src="/style/images/user/exp.png">500\'000<br/>';
echo'<img src="/style/images/user/level.png">14ур. - <img src="/style/images/user/exp.png">550\'000<br/>';
echo'<img src="/style/images/user/level.png">15ур. - <img src="/style/images/user/exp.png">600\'000<br/>';
echo'<img src="/style/images/user/level.png">16ур. - <img src="/style/images/user/exp.png">650\'000<br/>';
echo'<img src="/style/images/user/level.png">17ур. - <img src="/style/images/user/exp.png">700\'000<br/>';
echo'<img src="/style/images/user/level.png">18ур. - <img src="/style/images/user/exp.png">750\'000<br/>';
echo'<img src="/style/images/user/level.png">19ур. - <img src="/style/images/user/exp.png">800\'000<br/>';
echo'<img src="/style/images/user/level.png">20ур. - <img src="/style/images/user/exp.png">850\'000<br/>';
echo'<img src="/style/images/user/level.png">21ур. - <img src="/style/images/user/exp.png">900\'000<br/>';
echo'<img src="/style/images/user/level.png">22ур. - <img src="/style/images/user/exp.png">950\'000<br/>';
echo'<img src="/style/images/user/level.png">23ур. - <img src="/style/images/user/exp.png">1\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">24ур. - <img src="/style/images/user/exp.png">1\'100\'000<br/>';
echo'<img src="/style/images/user/level.png">25ур. - <img src="/style/images/user/exp.png">1\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">26ур. - <img src="/style/images/user/exp.png">1\'300\'000<br/>';
echo'<img src="/style/images/user/level.png">27ур. - <img src="/style/images/user/exp.png">1\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">28ур. - <img src="/style/images/user/exp.png">1\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">29ур. - <img src="/style/images/user/exp.png">1\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">30ур. - <img src="/style/images/user/exp.png">1\'700\'000<br/>';
echo'<img src="/style/images/user/level.png">31ур. - <img src="/style/images/user/exp.png">1\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">32ур. - <img src="/style/images/user/exp.png">1\'900\'000<br/>';
echo'<img src="/style/images/user/level.png">33ур. - <img src="/style/images/user/exp.png">2\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">34ур. - <img src="/style/images/user/exp.png">2\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">35ур. - <img src="/style/images/user/exp.png">2\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">36ур. - <img src="/style/images/user/exp.png">2\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">37ур. - <img src="/style/images/user/exp.png">2\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">38ур. - <img src="/style/images/user/exp.png">3\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">39ур. - <img src="/style/images/user/exp.png">3\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">40ур. - <img src="/style/images/user/exp.png">3\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">41ур. - <img src="/style/images/user/exp.png">3\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">42ур. - <img src="/style/images/user/exp.png">3\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">43ур. - <img src="/style/images/user/exp.png">4\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">44ур. - <img src="/style/images/user/exp.png">4\'250\'000<br/>';
echo'<img src="/style/images/user/level.png">45ур. - <img src="/style/images/user/exp.png">4\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">46ур. - <img src="/style/images/user/exp.png">4\'750\'000<br/>';
echo'<img src="/style/images/user/level.png">47ур. - <img src="/style/images/user/exp.png">5\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">48ур. - <img src="/style/images/user/exp.png">5\'300\'000<br/>';
echo'<img src="/style/images/user/level.png">49ур. - <img src="/style/images/user/exp.png">5\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">50ур. - <img src="/style/images/user/exp.png">5\'900\'000<br/>';
echo'<img src="/style/images/user/level.png">51ур. - <img src="/style/images/user/exp.png">6\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">52ур. - <img src="/style/images/user/exp.png">6\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">53ур. - <img src="/style/images/user/exp.png">6\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">54ур. - <img src="/style/images/user/exp.png">7\'150\'000<br/>';
echo'<img src="/style/images/user/level.png">55ур. - <img src="/style/images/user/exp.png">7\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">56ур. - <img src="/style/images/user/exp.png">7\'850\'000<br/>';
echo'<img src="/style/images/user/level.png">57ур. - <img src="/style/images/user/exp.png">8\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">58ур. - <img src="/style/images/user/exp.png">8\'550\'000<br/>';
echo'<img src="/style/images/user/level.png">59ур. - <img src="/style/images/user/exp.png">8\'900\'000<br/>';
echo'<img src="/style/images/user/level.png">60ур. - <img src="/style/images/user/exp.png">9\'300\'000<br/>';
echo'<img src="/style/images/user/level.png">61ур. - <img src="/style/images/user/exp.png">9\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">62ур. - <img src="/style/images/user/exp.png">9\'900\'000<br/>';
echo'<img src="/style/images/user/level.png">63ур. - <img src="/style/images/user/exp.png">10\'100\'000<br/>';
echo'<img src="/style/images/user/level.png">64ур. - <img src="/style/images/user/exp.png">10\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">65ур. - <img src="/style/images/user/exp.png">10\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">66ур. - <img src="/style/images/user/exp.png">11\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">67ур. - <img src="/style/images/user/exp.png">11\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">68ур. - <img src="/style/images/user/exp.png">12\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">69ур. - <img src="/style/images/user/exp.png">12\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">70ур. - <img src="/style/images/user/exp.png">12\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">71ур. - <img src="/style/images/user/exp.png">13\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">72ур. - <img src="/style/images/user/exp.png">13\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">73ур. - <img src="/style/images/user/exp.png">14\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">74ур. - <img src="/style/images/user/exp.png">14\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">75ур. - <img src="/style/images/user/exp.png">14\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">76ур. - <img src="/style/images/user/exp.png">15\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">77ур. - <img src="/style/images/user/exp.png">15\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">78ур. - <img src="/style/images/user/exp.png">16\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">79ур. - <img src="/style/images/user/exp.png">16\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">80ур. - <img src="/style/images/user/exp.png">17\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">81ур. - <img src="/style/images/user/exp.png">17\'550\'000<br/>';
echo'<img src="/style/images/user/level.png">82ур. - <img src="/style/images/user/exp.png">18\'100\'000<br/>';
echo'<img src="/style/images/user/level.png">83ур. - <img src="/style/images/user/exp.png">18\'650\'000<br/>';
echo'<img src="/style/images/user/level.png">84ур. - <img src="/style/images/user/exp.png">18\'900\'000<br/>';
echo'<img src="/style/images/user/level.png">85ур. - <img src="/style/images/user/exp.png">19\'300\'000<br/>';
echo'<img src="/style/images/user/level.png">86ур. - <img src="/style/images/user/exp.png">19\'850\'000<br/>';
echo'<img src="/style/images/user/level.png">87ур. - <img src="/style/images/user/exp.png">20\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">88ур. - <img src="/style/images/user/exp.png">21\'950\'000<br/>';
echo'<img src="/style/images/user/level.png">89ур. - <img src="/style/images/user/exp.png">22\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">90ур. - <img src="/style/images/user/exp.png">23\'050\'000<br/>';
echo'<img src="/style/images/user/level.png">91ур. - <img src="/style/images/user/exp.png">23\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">92ур. - <img src="/style/images/user/exp.png">24\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">93ур. - <img src="/style/images/user/exp.png">24\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">94ур. - <img src="/style/images/user/exp.png">25\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">95ур. - <img src="/style/images/user/exp.png">26\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">96ур. - <img src="/style/images/user/exp.png">27\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">97ур. - <img src="/style/images/user/exp.png">28\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">98ур. - <img src="/style/images/user/exp.png">30\'100\'000<br/>';
echo'<img src="/style/images/user/level.png">99ур. - <img src="/style/images/user/exp.png">31\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">100ур. - <img src="/style/images/user/exp.png">31\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">101ур. - <img src="/style/images/user/exp.png">32\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">102ур. - <img src="/style/images/user/exp.png">32\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">103ур. - <img src="/style/images/user/exp.png">33\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">104ур. - <img src="/style/images/user/exp.png">33\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">105ур. - <img src="/style/images/user/exp.png">34\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">106ур. - <img src="/style/images/user/exp.png">34\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">107ур. - <img src="/style/images/user/exp.png">35\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">108ур. - <img src="/style/images/user/exp.png">35\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">109ур. - <img src="/style/images/user/exp.png">36\'120\'000<br/>';
echo'<img src="/style/images/user/level.png">110ур. - <img src="/style/images/user/exp.png">36\'720\'000<br/>';
echo'<img src="/style/images/user/level.png">111ур. - <img src="/style/images/user/exp.png">37\'320\'000<br/>';
echo'<img src="/style/images/user/level.png">112ур. - <img src="/style/images/user/exp.png">38\'100\'000<br/>';
echo'<img src="/style/images/user/level.png">113ур. - <img src="/style/images/user/exp.png">38\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">114ур. - <img src="/style/images/user/exp.png">39\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">115ур. - <img src="/style/images/user/exp.png">40\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">116ур. - <img src="/style/images/user/exp.png">40\'900\'000<br/>';
echo'<img src="/style/images/user/level.png">117ур. - <img src="/style/images/user/exp.png">41\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">118ур. - <img src="/style/images/user/exp.png">42\'300\'000<br/>';
echo'<img src="/style/images/user/level.png">119ур. - <img src="/style/images/user/exp.png">43\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">120ур. - <img src="/style/images/user/exp.png">43\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">121ур. - <img src="/style/images/user/exp.png">44\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">122ур. - <img src="/style/images/user/exp.png">45\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">123ур. - <img src="/style/images/user/exp.png">46\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">124ур. - <img src="/style/images/user/exp.png">47\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">125ур. - <img src="/style/images/user/exp.png">47\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">126ур. - <img src="/style/images/user/exp.png">48\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">127ур. - <img src="/style/images/user/exp.png">49\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">128ур. - <img src="/style/images/user/exp.png">50\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">129ур. - <img src="/style/images/user/exp.png">51\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">130ур. - <img src="/style/images/user/exp.png">51\'900\'000<br/>';
echo'<img src="/style/images/user/level.png">131ур. - <img src="/style/images/user/exp.png">52\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">132ур. - <img src="/style/images/user/exp.png">53\'700\'000<br/>';
echo'<img src="/style/images/user/level.png">133ур. - <img src="/style/images/user/exp.png">54\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">134ур. - <img src="/style/images/user/exp.png">55\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">135ур. - <img src="/style/images/user/exp.png">56\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">136ур. - <img src="/style/images/user/exp.png">57\'300\'000<br/>';
echo'<img src="/style/images/user/level.png">137ур. - <img src="/style/images/user/exp.png">58\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">138ур. - <img src="/style/images/user/exp.png">59\'100\'000<br/>';
echo'<img src="/style/images/user/level.png">139ур. - <img src="/style/images/user/exp.png">60\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">140ур. - <img src="/style/images/user/exp.png">61\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">141ур. - <img src="/style/images/user/exp.png">62\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">142ур. - <img src="/style/images/user/exp.png">63\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">143ур. - <img src="/style/images/user/exp.png">64\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">144ур. - <img src="/style/images/user/exp.png">65\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">145ур. - <img src="/style/images/user/exp.png">66\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">146ур. - <img src="/style/images/user/exp.png">67\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">147ур. - <img src="/style/images/user/exp.png">68\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">148ур. - <img src="/style/images/user/exp.png">69\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">149ур. - <img src="/style/images/user/exp.png">70\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">150ур. - <img src="/style/images/user/exp.png">71\'000\'000<br/>';
echo'</span>';
echo'</div>';
echo'</div>';
}

#-Таблица опыта-#
echo'<div class="line_1"></div>';
echo'<li><a href="/knowledge_basa?sort=table_exp&spr=user_exp"><img src="/style/images/user/exp.png" alt=""/> Таблица прокачки игрока</a></li>';
if($_GET['spr'] == 'user_exp'){
echo'<div class="line_1_m"></div>';
echo'<div class="page">';
echo'<div style="padding: 5px;">';
echo'<span class="whit">';
echo'<img src="/style/images/user/level.png">1 ур. - <img src="/style/images/user/exp.png">0<br/>';
echo'<img src="/style/images/user/level.png">2 ур. - <img src="/style/images/user/exp.png">500<br/>';
echo'<img src="/style/images/user/level.png">3 ур. - <img src="/style/images/user/exp.png">1\'500<br/>';
echo'<img src="/style/images/user/level.png">4 ур. - <img src="/style/images/user/exp.png">3\'200<br/>';
echo'<img src="/style/images/user/level.png">5 ур. - <img src="/style/images/user/exp.png">4\'500<br/>';
echo'<img src="/style/images/user/level.png">6 ур. - <img src="/style/images/user/exp.png">6\'000<br/>';
echo'<img src="/style/images/user/level.png">7 ур. - <img src="/style/images/user/exp.png">8\'800<br/>';
echo'<img src="/style/images/user/level.png">8 ур. - <img src="/style/images/user/exp.png">10\'200<br/>';
echo'<img src="/style/images/user/level.png">9 ур. - <img src="/style/images/user/exp.png">13\'200<br/>';
echo'<img src="/style/images/user/level.png">10 ур. - <img src="/style/images/user/exp.png">16\'000<br/>';
echo'<img src="/style/images/user/level.png">12 ур. - <img src="/style/images/user/exp.png">18\'900<br/>';
echo'<img src="/style/images/user/level.png">12 ур. - <img src="/style/images/user/exp.png">21\'100<br/>';
echo'<img src="/style/images/user/level.png">13 ур. - <img src="/style/images/user/exp.png">25\'000<br/>';
echo'<img src="/style/images/user/level.png">14 ур. - <img src="/style/images/user/exp.png">29\'000<br/>';
echo'<img src="/style/images/user/level.png">15 ур. - <img src="/style/images/user/exp.png">35\'000<br/>';
echo'<img src="/style/images/user/level.png">16 ур. - <img src="/style/images/user/exp.png">47\'000<br/>';
echo'<img src="/style/images/user/level.png">17 ур. - <img src="/style/images/user/exp.png">56\'000<br/>';
echo'<img src="/style/images/user/level.png">18 ур. - <img src="/style/images/user/exp.png">65\'000<br/>';
echo'<img src="/style/images/user/level.png">19 ур. - <img src="/style/images/user/exp.png">73\'000<br/>';
echo'<img src="/style/images/user/level.png">20 ур. - <img src="/style/images/user/exp.png">85\'000<br/>';
echo'<img src="/style/images/user/level.png">21 ур. - <img src="/style/images/user/exp.png">94\'000<br/>';
echo'<img src="/style/images/user/level.png">22 ур. - <img src="/style/images/user/exp.png">105\'000<br/>';
echo'<img src="/style/images/user/level.png">23 ур. - <img src="/style/images/user/exp.png">115\'000<br/>';
echo'<img src="/style/images/user/level.png">24 ур. - <img src="/style/images/user/exp.png">130\'000<br/>';
echo'<img src="/style/images/user/level.png">25 ур. - <img src="/style/images/user/exp.png">145\'000<br/>';
echo'<img src="/style/images/user/level.png">26 ур. - <img src="/style/images/user/exp.png">156\'000<br/>';
echo'<img src="/style/images/user/level.png">27 ур. - <img src="/style/images/user/exp.png">170\'000<br/>';
echo'<img src="/style/images/user/level.png">28 ур. - <img src="/style/images/user/exp.png">185\'000<br/>';
echo'<img src="/style/images/user/level.png">29 ур. - <img src="/style/images/user/exp.png">210\'000<br/>';
echo'<img src="/style/images/user/level.png">30 ур. - <img src="/style/images/user/exp.png">230\'000<br/>';
echo'<img src="/style/images/user/level.png">31 ур. - <img src="/style/images/user/exp.png">245\'000<br/>';
echo'<img src="/style/images/user/level.png">32 ур. - <img src="/style/images/user/exp.png">263\'000<br/>';
echo'<img src="/style/images/user/level.png">33 ур. - <img src="/style/images/user/exp.png">281\'000<br/>';
echo'<img src="/style/images/user/level.png">34 ур. - <img src="/style/images/user/exp.png">290\'000<br/>';
echo'<img src="/style/images/user/level.png">35 ур. - <img src="/style/images/user/exp.png">340\'000<br/>';
echo'<img src="/style/images/user/level.png">36 ур. - <img src="/style/images/user/exp.png">380\'000<br/>';
echo'<img src="/style/images/user/level.png">37 ур. - <img src="/style/images/user/exp.png">420\'000<br/>';
echo'<img src="/style/images/user/level.png">38 ур. - <img src="/style/images/user/exp.png">460\'000<br/>';
echo'<img src="/style/images/user/level.png">39 ур. - <img src="/style/images/user/exp.png">500\'000<br/>';
echo'<img src="/style/images/user/level.png">40 ур. - <img src="/style/images/user/exp.png">540\'000<br/>';
echo'<img src="/style/images/user/level.png">41 ур. - <img src="/style/images/user/exp.png">580\'000<br/>';
echo'<img src="/style/images/user/level.png">42 ур. - <img src="/style/images/user/exp.png">620\'000<br/>';
echo'<img src="/style/images/user/level.png">43 ур. - <img src="/style/images/user/exp.png">660\'000<br/>';
echo'<img src="/style/images/user/level.png">44 ур. - <img src="/style/images/user/exp.png">700\'000<br/>';
echo'<img src="/style/images/user/level.png">45 ур. - <img src="/style/images/user/exp.png">740\'000<br/>';
echo'<img src="/style/images/user/level.png">46 ур. - <img src="/style/images/user/exp.png">780\'000<br/>';
echo'<img src="/style/images/user/level.png">47 ур. - <img src="/style/images/user/exp.png">820\'000<br/>';
echo'<img src="/style/images/user/level.png">48 ур. - <img src="/style/images/user/exp.png">860\'000<br/>';
echo'<img src="/style/images/user/level.png">49 ур. - <img src="/style/images/user/exp.png">900\'000<br/>';
echo'<img src="/style/images/user/level.png">50 ур. - <img src="/style/images/user/exp.png">940\'000<br/>';
echo'<img src="/style/images/user/level.png">51 ур. - <img src="/style/images/user/exp.png">980\'000<br/>';
echo'<img src="/style/images/user/level.png">52 ур. - <img src="/style/images/user/exp.png">1\'020\'000<br/>';
echo'<img src="/style/images/user/level.png">53 ур. - <img src="/style/images/user/exp.png">1\'060\'000<br/>';
echo'<img src="/style/images/user/level.png">54 ур. - <img src="/style/images/user/exp.png">1\'100\'000<br/>';
echo'<img src="/style/images/user/level.png">55 ур. - <img src="/style/images/user/exp.png">1\'140\'000<br/>';
echo'<img src="/style/images/user/level.png">56 ур. - <img src="/style/images/user/exp.png">1\'180\'000<br/>';
echo'<img src="/style/images/user/level.png">57 ур. - <img src="/style/images/user/exp.png">1\'220\'000<br/>';
echo'<img src="/style/images/user/level.png">58 ур. - <img src="/style/images/user/exp.png">1\'260\'000<br/>';
echo'<img src="/style/images/user/level.png">59 ур. - <img src="/style/images/user/exp.png">1\'300\'000<br/>';
echo'<img src="/style/images/user/level.png">60 ур. - <img src="/style/images/user/exp.png">1\'340\'000<br/>';
echo'<img src="/style/images/user/level.png">61 ур. - <img src="/style/images/user/exp.png">1\'380\'000<br/>';
echo'<img src="/style/images/user/level.png">62 ур. - <img src="/style/images/user/exp.png">1\'420\'000<br/>';
echo'<img src="/style/images/user/level.png">63 ур. - <img src="/style/images/user/exp.png">1\'460\'000<br/>';
echo'<img src="/style/images/user/level.png">64 ур. - <img src="/style/images/user/exp.png">1\'500\'000<br/>';
echo'<img src="/style/images/user/level.png">65 ур. - <img src="/style/images/user/exp.png">1\'540\'000<br/>';
echo'<img src="/style/images/user/level.png">66 ур. - <img src="/style/images/user/exp.png">1\'580\'000<br/>';
echo'<img src="/style/images/user/level.png">67 ур. - <img src="/style/images/user/exp.png">1\'620\'000<br/>';
echo'<img src="/style/images/user/level.png">68 ур. - <img src="/style/images/user/exp.png">1\'660\'000<br/>';
echo'<img src="/style/images/user/level.png">69 ур. - <img src="/style/images/user/exp.png">1\'700\'000<br/>';
echo'<img src="/style/images/user/level.png">70 ур. - <img src="/style/images/user/exp.png">1\'740\'000<br/>';
echo'<img src="/style/images/user/level.png">71 ур. - <img src="/style/images/user/exp.png">2\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">72 ур. - <img src="/style/images/user/exp.png">2\'200\'000<br/>';
echo'<img src="/style/images/user/level.png">73 ур. - <img src="/style/images/user/exp.png">2\'400\'000<br/>';
echo'<img src="/style/images/user/level.png">74 ур. - <img src="/style/images/user/exp.png">2\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">75 ур. - <img src="/style/images/user/exp.png">2\'800\'000<br/>';
echo'<img src="/style/images/user/level.png">76 ур. - <img src="/style/images/user/exp.png">3\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">77 ур. - <img src="/style/images/user/exp.png">3\'300\'000<br/>';
echo'<img src="/style/images/user/level.png">78 ур. - <img src="/style/images/user/exp.png">3\'600\'000<br/>';
echo'<img src="/style/images/user/level.png">79 ур. - <img src="/style/images/user/exp.png">4\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">80 ур. - <img src="/style/images/user/exp.png">5\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">81 ур. - <img src="/style/images/user/exp.png">6\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">82 ур. - <img src="/style/images/user/exp.png">7\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">83 ур. - <img src="/style/images/user/exp.png">8\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">84 ур. - <img src="/style/images/user/exp.png">9\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">85 ур. - <img src="/style/images/user/exp.png">10\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">86 ур. - <img src="/style/images/user/exp.png">12\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">87 ур. - <img src="/style/images/user/exp.png">14\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">88 ур. - <img src="/style/images/user/exp.png">16\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">89 ур. - <img src="/style/images/user/exp.png">18\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">90 ур. - <img src="/style/images/user/exp.png">20\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">91 ур. - <img src="/style/images/user/exp.png">23\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">92 ур. - <img src="/style/images/user/exp.png">26\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">93 ур. - <img src="/style/images/user/exp.png">29\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">94 ур. - <img src="/style/images/user/exp.png">34\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">95 ур. - <img src="/style/images/user/exp.png">36\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">96 ур. - <img src="/style/images/user/exp.png">40\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">97 ур. - <img src="/style/images/user/exp.png">42\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">98 ур. - <img src="/style/images/user/exp.png">44\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">99 ур. - <img src="/style/images/user/exp.png">46\'000\'000<br/>';
echo'<img src="/style/images/user/level.png">100 ур. - <img src="/style/images/user/exp.png">50\'000\'000<br/>';
echo'</span>';
echo'</div>';
echo'</div>';
}

echo'<div class="line_1"></div>';
echo'<li><a href="/knowledge_basa"><img src="/style/images/body/back.png" alt=""/> Назад</a></li>';
echo'</div>';
echo'</div>';
?>