<?php
echo'<div class="body_list">';
echo'<div class="menulist">';
                                                                           /*ИГРОК*/
#-Почта-#
echo'<li><a href="/knowledge_basa?sort=user&spr=mail"><img src="/style/images/user/mail.png" alt=""/> Почта</a></li>';
if($_GET['spr'] == 'mail'){
echo'<div class="line_1_m"></div>';
echo'<div class="page">';
echo'<div style="padding: 5px;">';
echo'<span class="whit">';
echo'<img src="/style/images/user/mail.png" alt=""/><span class="yellow">Почта</span> - предназначена для личного общения с другими игроками.<br/>';
echo'Если вы у пользователя в <img src="/style/images/body/error.png"><span class="gray">Чёрном списке</span> или он запретил писать всем сообщения, то писать личные сообщения вы ему не сможете.<br/>';
echo'<img src="/style/images/body/imp.png" alt=""/> <span style="font-size:14px; color:#dc50ff;">Почта доступна с <img src="/style/images/user/level.png" alt=""/>30 ур.</span><br/>';
echo'<img src="/style/images/body/imp.png" alt=""/> <span style="font-size:14px; color:#dc50ff;">Сообщения которым более 10 дней автоматически удаляються</span><br/>';
echo'</span>';
echo'</div>';
echo'</div>';
}

#-Питомцы-#
echo'<div class="line_1"></div>';
echo'<li><a href="/knowledge_basa?sort=user&spr=pets"><img src="/style/images/body/pets.png" alt=""/> Питомцы</a></li>';
if($_GET['spr'] == 'pets'){
echo'<div class="line_1_m"></div>';
echo'<div class="page">';
echo'<div style="padding: 5px;">';
echo'<span class="whit">';
echo'<img src="/style/images/body/pets.png" alt=""/><span class="yellow">Питомцы</span> - заведи питомца и участвуй в боя питомцев.<br/>';

#-Из торговой лавки-#
echo'<img src="/style/images/body/torg.png" alt=""/><span class="blue">Питомцы из торговой лавки:</span><br/>';
echo'<div class="t_max">';
echo'<img src="/style/images/pets/mouse.jpg" class="t_img" alt=""/>';
echo'<div class="t_name"><img src="/style/images/quality/1.png" alt=""/><b>Мышь</b><br/> <span class="t_param"><img src="/style/images/user/sila.png" alt=""/>100 <img src="/style/images/user/zashita.png" alt=""/>100  <img src="/style/images/user/health.png" alt=""/>100</span><br/><img src="/style/images/pets/ability/thief.gif" alt=""/><span class="yellow">Способность: Везение</span></div>';
echo'</div>';
echo'<div class="t_max">';
echo'<img src="/style/images/pets/wolf.jpg" class="t_img" alt=""/>';
echo'<div class="t_name"><img src="/style/images/quality/1.png" alt=""/><b>Волк</b><br/> <span class="t_param"><img src="/style/images/user/sila.png" alt=""/>600 <img src="/style/images/user/zashita.png" alt=""/>600  <img src="/style/images/user/health.png" alt=""/>600</span><br/><img src="/style/images/pets/ability/absorb.gif" alt=""/><span class="yellow">Способность: Поглощение</span></div>';
echo'</div>';
echo'<div class="t_max">';
echo'<img src="/style/images/pets/lion.jpg" class="t_img" alt=""/>';
echo'<div class="t_name"><img src="/style/images/quality/1.png" alt=""/><b>Лев</b><br/> <span class="t_param"><img src="/style/images/user/sila.png" alt=""/>1100 <img src="/style/images/user/zashita.png" alt=""/>1100 <img src="/style/images/user/health.png" alt=""/>1100</span><br/><img src="/style/images/pets/ability/crete.gif" alt=""/><span class="yellow">Способность: Крит</span></div>';
echo'</div>';

#-Редкие питомцы-#
echo'<img src="/style/images/quality/5.png" alt=""/><span class="purple">Редкие питомцы:</span><br/>';
echo'<div class="t_max">';
echo'<img src="/style/images/pets/zmeeglav.jpg" class="t_img" alt=""/>';
echo'<div class="t_name"><img src="/style/images/quality/1.png" alt=""/><b>Змееглав</b><br/> <span class="t_param"><img src="/style/images/user/sila.png" alt=""/>2200 <img src="/style/images/user/zashita.png" alt=""/>2200  <img src="/style/images/user/health.png" alt=""/>2200</span><br/><img src="/style/images/pets/ability/dodge.gif" alt=""/><span class="yellow">Способность: Уворот</span></div>';
echo'</div>';
echo'<div class="t_max">';
echo'<img src="/style/images/pets/gelaus.jpg" class="t_img" alt=""/>';
echo'<div class="t_name"><img src="/style/images/quality/1.png" alt=""/><b>Гелаус</b><br/> <span class="t_param"><img src="/style/images/user/sila.png" alt=""/>4400 <img src="/style/images/user/zashita.png" alt=""/>4400  <img src="/style/images/user/health.png" alt=""/>4400</span><br/><img src="/style/images/pets/ability/treatment.gif" alt=""/><span class="yellow">Способность: Вампиризм</span></div>';
echo'</div>';

echo'Способности питомцев:<br/>';
echo'<img src="/style/images/pets/ability/thief.gif" alt=""/><span class="yellow"><u>Везение</u></span>: повышение получаемой награды во время боя.<br/>';
echo'<img src="/style/images/pets/ability/absorb.gif" alt=""/><span class="yellow"><u>Поглощение</u></span>: поглощает половину урона наносимого другим питомцем.<br/>';
echo'<img src="/style/images/pets/ability/crete.gif" alt=""/><span class="yellow"><u>Крит</u></span>: питомец наносит в два раза больше урона.<br/>';
echo'<img src="/style/images/pets/ability/dodge.gif" alt=""/><span class="yellow"><u>Уворот</u></span>: полностью уворачивается от урона.<br/>';
echo'<img src="/style/images/pets/ability/treatment.gif" alt=""/><span class="yellow"><u>Вампиризм</u></span>: восстанавливает 30% здоровья от максимального.<br/>';
echo'<div style="padding: 2px;"></div>';
echo'<img src="/style/images/body/imp.png" alt=""/> <span style="font-size:14px; color:#dc50ff;">Максимальный уровень тренировки <img src="/style/images/user/level.png" alt=""/>100</span><br/>';
echo'</span>';
echo'</div>';
echo'</div>';
}

#-Сундуки-#
echo'<div class="line_1"></div>';
echo'<li><a href="/knowledge_basa?sort=user&spr=sunduk"><img src="/style/images/body/chest.png" alt=""/> Сундуки</a></li>';
if($_GET['spr'] == 'sunduk'){
echo'<div class="line_1_m"></div>';
echo'<div class="page">';
echo'<div style="padding: 5px;">';
echo'<span class="whit">';
echo'<img src="/style/images/body/chest.png" alt=""/><span class="yellow">Сундуки</span> - вы получите различные бонусы открыв сундук.<br/>';
echo'Виды <img src="/style/images/body/chest.png" alt=""/><span class="gray">Сундуков</span>:<br/>';
echo'<div style="padding: 2px;"></div>';
echo'<img src="/style/images/body/chest.png" alt=""/><span class="gray">Обычный сундук</span> - награда <img src="/style/images/user/exp.png"/><span class="gray">Опыт</span> и <img src="/style/images/many/silver.png"/><span class="gray">Серебро</span>. С вероятностью 3% вы можете выиграть <img src="/style/images/many/silver.png"/>100.000 серебра.<br/>';
echo'<img src="/style/images/body/chest.png" alt=""/><span class="gray">Древний сундук</span> - награда <img src="/style/images/user/exp.png"/><span class="gray">Опыт</span> и одна вещь <img src="/style/images/body/torg.png"/><span class="gray">Торговой лавки</span> уровень которой ниже или равен вашему из.<br/>';
echo'<img src="/style/images/body/chest.png" alt=""/><span class="gray">Золотой сундук</span> - награда <img src="/style/images/user/exp.png"/><span class="gray">Опыт</span> и <img src="/style/images/body/traing.png"/><span class="gray">Скрытая вещь</span> или <img src="/style/images/many/gold.png"/><span class="gray">Золото</span>.<br/>';
echo'<div style="padding: 2px;"></div>';
echo'<img src="/style/images/body/imp.png" alt=""/> <span style="font-size:14px; color:#dc50ff;">Срок хранения сундуков 5 дней</span><br/>';
echo'<img src="/style/images/body/imp.png" alt=""/> <span style="font-size:14px; color:#dc50ff;">Открыть сундук можно <img src="/style/images/body/key.png" alt=""/>Ключом или за <img src="/style/images/many/gold.png" alt=""/>Золото</span><br/>';
echo'</span>';
echo'</div>';
echo'</div>';
}

#-Сумка-#
echo'<div class="line_1"></div>';
echo'<li><a href="/knowledge_basa?sort=user&spr=bag"><img src="/style/images/body/sumka.png" alt=""/> Сумка</a></li>';
if($_GET['spr'] == 'bag'){
echo'<div class="line_1_m"></div>';
echo'<div class="page">';
echo'<div style="padding: 5px;">';
echo'<span class="whit">';
echo'<img src="/style/images/body/sumka.png" alt=""/><span class="yellow">Сумка</span> - предназначена для хранения <span class="gray">Снаряжения</span> и <span class="gray">Зелья</span>.<br/>';
echo'<img src="/style/images/body/imp.png" alt=""/> <span style="font-size:14px; color:#dc50ff;">Кол-во места не ограничено</span><br/>';
echo'</span>';
echo'</div>';
echo'</div>';
}

#-Тренировка-#
echo'<div class="line_1"></div>';
echo'<li><a href="/knowledge_basa?sort=user&spr=train"><img src="/style/images/body/traing.png" alt=""/> Тренировка</a></li>';
if($_GET['spr'] == 'train'){
echo'<div class="line_1_m"></div>';
echo'<div class="page">';
echo'<div style="padding: 5px;">';
echo'<span class="whit">';
echo'<img src="/style/images/body/traing.png" alt=""/><span class="yellow">Тренировка</span> - прокачивайте ваши параметры и становитесь сильнее.<br/>';
echo'<div style="padding: 2px;"></div>';
echo'<img src="/style/images/user/sila.png"/><span class="gray">Сила</span> влияет на урон который вы нанесете своему врагу. Чем выше сила тем больше урона вы сможете нанести своему врагу.<br/>';
echo'<img src="/style/images/user/zashita.png"/><span class="gray">Защита</span> снижает урон к минимуму. Чем выше защита тем меньше урон.<br/>';
echo'<img src="/style/images/user/health.png"/><span class="gray">Здоровье</span> определяет максимальное количество здоровья.<br/>';

echo'<img src="/style/images/user/sila.png"/><span class="gray">Сила</span> и <img src="/style/images/user/zashita.png"/><span class="gray">Защита</span>:<br/>';
echo'<img src="/style/images/user/level.png"/>2 - <img src="/style/images/many/silver.png"/>50<br/>';
echo'<img src="/style/images/user/level.png"/>3 - <img src="/style/images/many/silver.png"/>200<br/>';
echo'<img src="/style/images/user/level.png"/>4 - <img src="/style/images/many/silver.png"/>450<br/>';
echo'<img src="/style/images/user/level.png"/>5 - <img src="/style/images/many/silver.png"/>800<br/>';
echo'<img src="/style/images/user/level.png"/>6 - <img src="/style/images/many/silver.png"/>1250<br/>';
echo'<img src="/style/images/user/level.png"/>7 - <img src="/style/images/many/silver.png"/>1800<br/>';
echo'<img src="/style/images/user/level.png"/>8 - <img src="/style/images/many/silver.png"/>2450<br/>';
echo'<img src="/style/images/user/level.png"/>9 - <img src="/style/images/many/silver.png"/>3200<br/>';
echo'<img src="/style/images/user/level.png"/>10 - <img src="/style/images/many/silver.png"/>4050<br/>';
echo'<img src="/style/images/user/level.png"/>11 - <img src="/style/images/many/gold.png"/>10<br/>';
echo'<img src="/style/images/user/level.png"/>12 - <img src="/style/images/many/silver.png"/>6050<br/>';
echo'<img src="/style/images/user/level.png"/>13 - <img src="/style/images/many/silver.png"/>7200<br/>';
echo'<img src="/style/images/user/level.png"/>14 - <img src="/style/images/many/silver.png"/>8450<br/>';
echo'<img src="/style/images/user/level.png"/>15 - <img src="/style/images/many/silver.png"/>9800<br/>';
echo'<img src="/style/images/user/level.png"/>16 - <img src="/style/images/many/silver.png"/>11250<br/>';
echo'<img src="/style/images/user/level.png"/>17 - <img src="/style/images/many/silver.png"/>12800<br/>';
echo'<img src="/style/images/user/level.png"/>18 - <img src="/style/images/many/silver.png"/>14450<br/>';
echo'<img src="/style/images/user/level.png"/>19 - <img src="/style/images/many/silver.png"/>16200<br/>';
echo'<img src="/style/images/user/level.png"/>20 - <img src="/style/images/many/silver.png"/>18050<br/>';
echo'<img src="/style/images/user/level.png"/>21 - <img src="/style/images/many/gold.png"/>20<br/>';
echo'<img src="/style/images/user/level.png"/>22 - <img src="/style/images/many/silver.png"/>22050<br/>';
echo'<img src="/style/images/user/level.png"/>23 - <img src="/style/images/many/silver.png"/>24200<br/>';
echo'<img src="/style/images/user/level.png"/>24 - <img src="/style/images/many/silver.png"/>26450<br/>';
echo'<img src="/style/images/user/level.png"/>25 - <img src="/style/images/many/silver.png"/>28800<br/>';
echo'<img src="/style/images/user/level.png"/>26 - <img src="/style/images/many/silver.png"/>31250<br/>';
echo'<img src="/style/images/user/level.png"/>27 - <img src="/style/images/many/silver.png"/>33800<br/>';
echo'<img src="/style/images/user/level.png"/>28 - <img src="/style/images/many/silver.png"/>36450<br/>';
echo'<img src="/style/images/user/level.png"/>29 - <img src="/style/images/many/silver.png"/>39200<br/>';
echo'<img src="/style/images/user/level.png"/>30 - <img src="/style/images/many/silver.png"/>42050<br/>';
echo'<img src="/style/images/user/level.png"/>31 - <img src="/style/images/many/gold.png"/>30<br/>';
echo'<img src="/style/images/user/level.png"/>32 - <img src="/style/images/many/silver.png"/>48050<br/>';
echo'<img src="/style/images/user/level.png"/>33 - <img src="/style/images/many/silver.png"/>51200<br/>';
echo'<img src="/style/images/user/level.png"/>34 - <img src="/style/images/many/silver.png"/>54450<br/>';
echo'<img src="/style/images/user/level.png"/>35 - <img src="/style/images/many/silver.png"/>57800<br/>';
echo'<img src="/style/images/user/level.png"/>36 - <img src="/style/images/many/silver.png"/>61250<br/>';
echo'<img src="/style/images/user/level.png"/>37 - <img src="/style/images/many/silver.png"/>64800<br/>';
echo'<img src="/style/images/user/level.png"/>38 - <img src="/style/images/many/silver.png"/>68450<br/>';
echo'<img src="/style/images/user/level.png"/>39 - <img src="/style/images/many/silver.png"/>72200<br/>';
echo'<img src="/style/images/user/level.png"/>40 - <img src="/style/images/many/silver.png"/>76050<br/>';
echo'<img src="/style/images/user/level.png"/>41 - <img src="/style/images/many/gold.png"/>40<br/>';
echo'<img src="/style/images/user/level.png"/>42 - <img src="/style/images/many/silver.png"/>84050<br/>';
echo'<img src="/style/images/user/level.png"/>43 - <img src="/style/images/many/silver.png"/>88200<br/>';
echo'<img src="/style/images/user/level.png"/>44 - <img src="/style/images/many/silver.png"/>92450<br/>';
echo'<img src="/style/images/user/level.png"/>45 - <img src="/style/images/many/silver.png"/>96800<br/>';
echo'<img src="/style/images/user/level.png"/>46 - <img src="/style/images/many/silver.png"/>101250<br/>';
echo'<img src="/style/images/user/level.png"/>47 - <img src="/style/images/many/silver.png"/>105800<br/>';
echo'<img src="/style/images/user/level.png"/>48 - <img src="/style/images/many/silver.png"/>110450<br/>';
echo'<img src="/style/images/user/level.png"/>49 - <img src="/style/images/many/silver.png"/>115200<br/>';
echo'<img src="/style/images/user/level.png"/>50 - <img src="/style/images/many/silver.png"/>120050<br/>';
echo'<img src="/style/images/user/level.png"/>51 - <img src="/style/images/many/gold.png"/>50<br/>';
echo'<img src="/style/images/user/level.png"/>52 - <img src="/style/images/many/silver.png"/>130050<br/>';
echo'<img src="/style/images/user/level.png"/>53 - <img src="/style/images/many/silver.png"/>135200<br/>';
echo'<img src="/style/images/user/level.png"/>54 - <img src="/style/images/many/silver.png"/>140450<br/>';
echo'<img src="/style/images/user/level.png"/>55 - <img src="/style/images/many/silver.png"/>145800<br/>';
echo'<img src="/style/images/user/level.png"/>56 - <img src="/style/images/many/silver.png"/>151250<br/>';
echo'<img src="/style/images/user/level.png"/>57 - <img src="/style/images/many/silver.png"/>156800<br/>';
echo'<img src="/style/images/user/level.png"/>58 - <img src="/style/images/many/silver.png"/>162450<br/>';
echo'<img src="/style/images/user/level.png"/>59 - <img src="/style/images/many/silver.png"/>168200<br/>';
echo'<img src="/style/images/user/level.png"/>60 - <img src="/style/images/many/silver.png"/>174050<br/>';
echo'<img src="/style/images/user/level.png"/>61 - <img src="/style/images/many/gold.png"/>60<br/>';
echo'<img src="/style/images/user/level.png"/>62 - <img src="/style/images/many/silver.png"/>186050<br/>';
echo'<img src="/style/images/user/level.png"/>63 - <img src="/style/images/many/silver.png"/>192200<br/>';
echo'<img src="/style/images/user/level.png"/>64 - <img src="/style/images/many/silver.png"/>198450<br/>';
echo'<img src="/style/images/user/level.png"/>65 - <img src="/style/images/many/silver.png"/>204800<br/>';
echo'<img src="/style/images/user/level.png"/>66 - <img src="/style/images/many/silver.png"/>211250<br/>';
echo'<img src="/style/images/user/level.png"/>67 - <img src="/style/images/many/silver.png"/>217800<br/>';
echo'<img src="/style/images/user/level.png"/>68 - <img src="/style/images/many/silver.png"/>224450<br/>';
echo'<img src="/style/images/user/level.png"/>69 - <img src="/style/images/many/silver.png"/>231200<br/>';
echo'<img src="/style/images/user/level.png"/>70 - <img src="/style/images/many/silver.png"/>238050<br/>';
echo'<img src="/style/images/user/level.png"/>71 - <img src="/style/images/many/gold.png"/>70<br/>';
echo'<img src="/style/images/user/level.png"/>72 - <img src="/style/images/many/silver.png"/>252050<br/>';
echo'<img src="/style/images/user/level.png"/>73 - <img src="/style/images/many/silver.png"/>259200<br/>';
echo'<img src="/style/images/user/level.png"/>74 - <img src="/style/images/many/silver.png"/>266450<br/>';
echo'<img src="/style/images/user/level.png"/>75 - <img src="/style/images/many/silver.png"/>273800<br/>';
echo'<img src="/style/images/user/level.png"/>76 - <img src="/style/images/many/silver.png"/>281250<br/>';
echo'<img src="/style/images/user/level.png"/>77 - <img src="/style/images/many/silver.png"/>288800<br/>';
echo'<img src="/style/images/user/level.png"/>78 - <img src="/style/images/many/silver.png"/>296450<br/>';
echo'<img src="/style/images/user/level.png"/>79 - <img src="/style/images/many/silver.png"/>304200<br/>';
echo'<img src="/style/images/user/level.png"/>80 - <img src="/style/images/many/silver.png"/>312050<br/>';
echo'<img src="/style/images/user/level.png"/>81 - <img src="/style/images/many/gold.png"/>80<br/>';
echo'<img src="/style/images/user/level.png"/>82 - <img src="/style/images/many/silver.png"/>328050<br/>';
echo'<img src="/style/images/user/level.png"/>83 - <img src="/style/images/many/silver.png"/>336200<br/>';
echo'<img src="/style/images/user/level.png"/>84 - <img src="/style/images/many/silver.png"/>344450<br/>';
echo'<img src="/style/images/user/level.png"/>85 - <img src="/style/images/many/silver.png"/>352800<br/>';
echo'<img src="/style/images/user/level.png"/>86 - <img src="/style/images/many/silver.png"/>361250<br/>';
echo'<img src="/style/images/user/level.png"/>87 - <img src="/style/images/many/silver.png"/>369800<br/>';
echo'<img src="/style/images/user/level.png"/>88 - <img src="/style/images/many/silver.png"/>378450<br/>';
echo'<img src="/style/images/user/level.png"/>89 - <img src="/style/images/many/silver.png"/>387200<br/>';
echo'<img src="/style/images/user/level.png"/>90 - <img src="/style/images/many/silver.png"/>396050<br/>';
echo'<img src="/style/images/user/level.png"/>91 - <img src="/style/images/many/gold.png"/>90<br/>';
echo'<img src="/style/images/user/level.png"/>92 - <img src="/style/images/many/silver.png"/>414050<br/>';
echo'<img src="/style/images/user/level.png"/>93 - <img src="/style/images/many/silver.png"/>423200<br/>';
echo'<img src="/style/images/user/level.png"/>94 - <img src="/style/images/many/silver.png"/>432450<br/>';
echo'<img src="/style/images/user/level.png"/>95 - <img src="/style/images/many/silver.png"/>441800<br/>';
echo'<img src="/style/images/user/level.png"/>96 - <img src="/style/images/many/silver.png"/>451250<br/>';
echo'<img src="/style/images/user/level.png"/>97 - <img src="/style/images/many/silver.png"/>460800<br/>';
echo'<img src="/style/images/user/level.png"/>98 - <img src="/style/images/many/silver.png"/>470450<br/>';
echo'<img src="/style/images/user/level.png"/>99 - <img src="/style/images/many/silver.png"/>480200<br/>';
echo'<img src="/style/images/user/level.png"/>100 - <img src="/style/images/many/silver.png"/>490050<br/>';
echo'<img src="/style/images/user/level.png"/>101 - <img src="/style/images/many/gold.png"/>1000<br/>';
echo'<img src="/style/images/user/level.png"/>102 - <img src="/style/images/many/silver.png"/>510050<br/>';
echo'<img src="/style/images/user/level.png"/>103 - <img src="/style/images/many/silver.png"/>520200<br/>';
echo'<img src="/style/images/user/level.png"/>104 - <img src="/style/images/many/silver.png"/>530450<br/>';
echo'<img src="/style/images/user/level.png"/>105 - <img src="/style/images/many/silver.png"/>540800<br/>';
echo'<img src="/style/images/user/level.png"/>106 - <img src="/style/images/many/silver.png"/>551250<br/>';
echo'<img src="/style/images/user/level.png"/>107 - <img src="/style/images/many/silver.png"/>561800<br/>';
echo'<img src="/style/images/user/level.png"/>108 - <img src="/style/images/many/silver.png"/>572450<br/>';
echo'<img src="/style/images/user/level.png"/>109 - <img src="/style/images/many/silver.png"/>583200<br/>';
echo'<img src="/style/images/user/level.png"/>110 - <img src="/style/images/many/silver.png"/>594050<br/>';
echo'<img src="/style/images/user/level.png"/>111 - <img src="/style/images/many/gold.png"/>1100<br/>';
echo'<img src="/style/images/user/level.png"/>112 - <img src="/style/images/many/silver.png"/>616050<br/>';
echo'<img src="/style/images/user/level.png"/>113 - <img src="/style/images/many/silver.png"/>627200<br/>';
echo'<img src="/style/images/user/level.png"/>114 - <img src="/style/images/many/silver.png"/>638450<br/>';
echo'<img src="/style/images/user/level.png"/>115 - <img src="/style/images/many/silver.png"/>649800<br/>';
echo'<img src="/style/images/user/level.png"/>116 - <img src="/style/images/many/silver.png"/>661250<br/>';
echo'<img src="/style/images/user/level.png"/>117 - <img src="/style/images/many/silver.png"/>672800<br/>';
echo'<img src="/style/images/user/level.png"/>118 - <img src="/style/images/many/silver.png"/>684450<br/>';
echo'<img src="/style/images/user/level.png"/>119 - <img src="/style/images/many/silver.png"/>696200<br/>';
echo'<img src="/style/images/user/level.png"/>120 - <img src="/style/images/many/silver.png"/>708050<br/>';
echo'<img src="/style/images/user/level.png"/>121 - <img src="/style/images/many/gold.png"/>1200<br/>';
echo'<img src="/style/images/user/level.png"/>122 - <img src="/style/images/many/silver.png"/>732050<br/>';
echo'<img src="/style/images/user/level.png"/>123 - <img src="/style/images/many/silver.png"/>744200<br/>';
echo'<img src="/style/images/user/level.png"/>124 - <img src="/style/images/many/silver.png"/>756450<br/>';
echo'<img src="/style/images/user/level.png"/>125 - <img src="/style/images/many/silver.png"/>768800<br/>';
echo'<img src="/style/images/user/level.png"/>126 - <img src="/style/images/many/silver.png"/>781250<br/>';
echo'<img src="/style/images/user/level.png"/>127 - <img src="/style/images/many/silver.png"/>793800<br/>';
echo'<img src="/style/images/user/level.png"/>128 - <img src="/style/images/many/silver.png"/>806450<br/>';
echo'<img src="/style/images/user/level.png"/>129 - <img src="/style/images/many/silver.png"/>819200<br/>';
echo'<img src="/style/images/user/level.png"/>130 - <img src="/style/images/many/silver.png"/>832050<br/>';
echo'<img src="/style/images/user/level.png"/>131 - <img src="/style/images/many/gold.png"/>1300<br/>';
echo'<img src="/style/images/user/level.png"/>132 - <img src="/style/images/many/silver.png"/>858050<br/>';
echo'<img src="/style/images/user/level.png"/>133 - <img src="/style/images/many/silver.png"/>871200<br/>';
echo'<img src="/style/images/user/level.png"/>134 - <img src="/style/images/many/silver.png"/>884450<br/>';
echo'<img src="/style/images/user/level.png"/>135 - <img src="/style/images/many/silver.png"/>897800<br/>';
echo'<img src="/style/images/user/level.png"/>136 - <img src="/style/images/many/silver.png"/>911250<br/>';
echo'<img src="/style/images/user/level.png"/>137 - <img src="/style/images/many/silver.png"/>924800<br/>';
echo'<img src="/style/images/user/level.png"/>138 - <img src="/style/images/many/silver.png"/>938450<br/>';
echo'<img src="/style/images/user/level.png"/>139 - <img src="/style/images/many/silver.png"/>952200<br/>';
echo'<img src="/style/images/user/level.png"/>140 - <img src="/style/images/many/silver.png"/>966050<br/>';
echo'<img src="/style/images/user/level.png"/>141 - <img src="/style/images/many/gold.png"/>1400<br/>';
echo'<img src="/style/images/user/level.png"/>142 - <img src="/style/images/many/silver.png"/>994050<br/>';
echo'<img src="/style/images/user/level.png"/>143 - <img src="/style/images/many/silver.png"/>1008200<br/>';
echo'<img src="/style/images/user/level.png"/>144 - <img src="/style/images/many/silver.png"/>1022450<br/>';
echo'<img src="/style/images/user/level.png"/>145 - <img src="/style/images/many/silver.png"/>1036800<br/>';
echo'<img src="/style/images/user/level.png"/>146 - <img src="/style/images/many/silver.png"/>1051250<br/>';
echo'<img src="/style/images/user/level.png"/>147 - <img src="/style/images/many/silver.png"/>1065800<br/>';
echo'<img src="/style/images/user/level.png"/>148 - <img src="/style/images/many/silver.png"/>1080450<br/>';
echo'<img src="/style/images/user/level.png"/>149 - <img src="/style/images/many/silver.png"/>1095200<br/>';
echo'<img src="/style/images/user/level.png"/>150 - <img src="/style/images/many/silver.png"/>1110050<br/>';
echo'<img src="/style/images/user/level.png"/>151 - <img src="/style/images/many/gold.png"/>1500<br/>';
echo'<img src="/style/images/user/level.png"/>152 - <img src="/style/images/many/silver.png"/>1140050<br/>';
echo'<img src="/style/images/user/level.png"/>153 - <img src="/style/images/many/silver.png"/>1155200<br/>';
echo'<img src="/style/images/user/level.png"/>154 - <img src="/style/images/many/silver.png"/>1170450<br/>';
echo'<img src="/style/images/user/level.png"/>155 - <img src="/style/images/many/silver.png"/>1185800<br/>';
echo'<img src="/style/images/user/level.png"/>156 - <img src="/style/images/many/silver.png"/>1201250<br/>';
echo'<img src="/style/images/user/level.png"/>157 - <img src="/style/images/many/silver.png"/>1216800<br/>';
echo'<img src="/style/images/user/level.png"/>158 - <img src="/style/images/many/silver.png"/>1232450<br/>';
echo'<img src="/style/images/user/level.png"/>159 - <img src="/style/images/many/silver.png"/>1248200<br/>';
echo'<img src="/style/images/user/level.png"/>160 - <img src="/style/images/many/silver.png"/>1264050<br/>';
echo'<img src="/style/images/user/level.png"/>161 - <img src="/style/images/many/gold.png"/>1600<br/>';
echo'<img src="/style/images/user/level.png"/>162 - <img src="/style/images/many/silver.png"/>1296050<br/>';
echo'<img src="/style/images/user/level.png"/>163 - <img src="/style/images/many/silver.png"/>1312200<br/>';
echo'<img src="/style/images/user/level.png"/>164 - <img src="/style/images/many/silver.png"/>1328450<br/>';
echo'<img src="/style/images/user/level.png"/>165 - <img src="/style/images/many/silver.png"/>1344800<br/>';
echo'<img src="/style/images/user/level.png"/>166 - <img src="/style/images/many/silver.png"/>1361250<br/>';
echo'<img src="/style/images/user/level.png"/>167 - <img src="/style/images/many/silver.png"/>1377800<br/>';
echo'<img src="/style/images/user/level.png"/>168 - <img src="/style/images/many/silver.png"/>1394450<br/>';
echo'<img src="/style/images/user/level.png"/>169 - <img src="/style/images/many/silver.png"/>1411200<br/>';
echo'<img src="/style/images/user/level.png"/>170 - <img src="/style/images/many/silver.png"/>1428050<br/>';
echo'<img src="/style/images/user/level.png"/>171 - <img src="/style/images/many/gold.png"/>1700<br/>';
echo'<img src="/style/images/user/level.png"/>172 - <img src="/style/images/many/silver.png"/>1462050<br/>';
echo'<img src="/style/images/user/level.png"/>173 - <img src="/style/images/many/silver.png"/>1479200<br/>';
echo'<img src="/style/images/user/level.png"/>174 - <img src="/style/images/many/silver.png"/>1496450<br/>';
echo'<img src="/style/images/user/level.png"/>175 - <img src="/style/images/many/silver.png"/>1513800<br/>';
echo'<img src="/style/images/user/level.png"/>176 - <img src="/style/images/many/silver.png"/>1531250<br/>';
echo'<img src="/style/images/user/level.png"/>177 - <img src="/style/images/many/silver.png"/>1548800<br/>';
echo'<img src="/style/images/user/level.png"/>178 - <img src="/style/images/many/silver.png"/>1566450<br/>';
echo'<img src="/style/images/user/level.png"/>179 - <img src="/style/images/many/silver.png"/>1584200<br/>';
echo'<img src="/style/images/user/level.png"/>180 - <img src="/style/images/many/silver.png"/>1602050<br/>';
echo'<img src="/style/images/user/level.png"/>181 - <img src="/style/images/many/gold.png"/>1800<br/>';
echo'<img src="/style/images/user/level.png"/>182 - <img src="/style/images/many/silver.png"/>1638050<br/>';
echo'<img src="/style/images/user/level.png"/>183 - <img src="/style/images/many/silver.png"/>1656200<br/>';
echo'<img src="/style/images/user/level.png"/>184 - <img src="/style/images/many/silver.png"/>1674450<br/>';
echo'<img src="/style/images/user/level.png"/>185 - <img src="/style/images/many/silver.png"/>1692800<br/>';
echo'<img src="/style/images/user/level.png"/>186 - <img src="/style/images/many/silver.png"/>1711250<br/>';
echo'<img src="/style/images/user/level.png"/>187 - <img src="/style/images/many/silver.png"/>1729800<br/>';
echo'<img src="/style/images/user/level.png"/>188 - <img src="/style/images/many/silver.png"/>1748450<br/>';
echo'<img src="/style/images/user/level.png"/>189 - <img src="/style/images/many/silver.png"/>1767200<br/>';
echo'<img src="/style/images/user/level.png"/>190 - <img src="/style/images/many/silver.png"/>1786050<br/>';
echo'<img src="/style/images/user/level.png"/>191 - <img src="/style/images/many/gold.png"/>1900<br/>';
echo'<img src="/style/images/user/level.png"/>192 - <img src="/style/images/many/silver.png"/>1824050<br/>';
echo'<img src="/style/images/user/level.png"/>193 - <img src="/style/images/many/silver.png"/>1843200<br/>';
echo'<img src="/style/images/user/level.png"/>194 - <img src="/style/images/many/silver.png"/>1862450<br/>';
echo'<img src="/style/images/user/level.png"/>195 - <img src="/style/images/many/silver.png"/>1881800<br/>';
echo'<img src="/style/images/user/level.png"/>196 - <img src="/style/images/many/silver.png"/>1901250<br/>';
echo'<img src="/style/images/user/level.png"/>197 - <img src="/style/images/many/silver.png"/>1920800<br/>';
echo'<img src="/style/images/user/level.png"/>198 - <img src="/style/images/many/silver.png"/>1940450<br/>';
echo'<img src="/style/images/user/level.png"/>199 - <img src="/style/images/many/silver.png"/>1960200<br/>';
echo'<img src="/style/images/user/level.png"/>200 - <img src="/style/images/many/silver.png"/>1980050<br/><br/>';

echo'<img src="/style/images/user/health.png"/><span class="gray">Здоровье:</span><br/>';
echo'<img src="/style/images/user/level.png"/>2 - <img src="/style/images/many/silver.png"/>100<br/>';
echo'<img src="/style/images/user/level.png"/>3 - <img src="/style/images/many/silver.png"/>400<br/>';
echo'<img src="/style/images/user/level.png"/>4 - <img src="/style/images/many/silver.png"/>900<br/>';
echo'<img src="/style/images/user/level.png"/>5 - <img src="/style/images/many/silver.png"/>1600<br/>';
echo'<img src="/style/images/user/level.png"/>6 - <img src="/style/images/many/silver.png"/>2500<br/>';
echo'<img src="/style/images/user/level.png"/>7 - <img src="/style/images/many/silver.png"/>3600<br/>';
echo'<img src="/style/images/user/level.png"/>8 - <img src="/style/images/many/silver.png"/>4900<br/>';
echo'<img src="/style/images/user/level.png"/>9 - <img src="/style/images/many/silver.png"/>6400<br/>';
echo'<img src="/style/images/user/level.png"/>10 - <img src="/style/images/many/silver.png"/>8100<br/>';
echo'<img src="/style/images/user/level.png"/>11 - <img src="/style/images/many/gold.png"/>20<br/>';
echo'<img src="/style/images/user/level.png"/>12 - <img src="/style/images/many/silver.png"/>12100<br/>';
echo'<img src="/style/images/user/level.png"/>13 - <img src="/style/images/many/silver.png"/>14400<br/>';
echo'<img src="/style/images/user/level.png"/>14 - <img src="/style/images/many/silver.png"/>16900<br/>';
echo'<img src="/style/images/user/level.png"/>15 - <img src="/style/images/many/silver.png"/>19600<br/>';
echo'<img src="/style/images/user/level.png"/>16 - <img src="/style/images/many/silver.png"/>22500<br/>';
echo'<img src="/style/images/user/level.png"/>17 - <img src="/style/images/many/silver.png"/>25600<br/>';
echo'<img src="/style/images/user/level.png"/>18 - <img src="/style/images/many/silver.png"/>28900<br/>';
echo'<img src="/style/images/user/level.png"/>19 - <img src="/style/images/many/silver.png"/>32400<br/>';
echo'<img src="/style/images/user/level.png"/>20 - <img src="/style/images/many/silver.png"/>36100<br/>';
echo'<img src="/style/images/user/level.png"/>21 - <img src="/style/images/many/gold.png"/>40<br/>';
echo'<img src="/style/images/user/level.png"/>22 - <img src="/style/images/many/silver.png"/>44100<br/>';
echo'<img src="/style/images/user/level.png"/>23 - <img src="/style/images/many/silver.png"/>48400<br/>';
echo'<img src="/style/images/user/level.png"/>24 - <img src="/style/images/many/silver.png"/>52900<br/>';
echo'<img src="/style/images/user/level.png"/>25 - <img src="/style/images/many/silver.png"/>57600<br/>';
echo'<img src="/style/images/user/level.png"/>26 - <img src="/style/images/many/silver.png"/>62500<br/>';
echo'<img src="/style/images/user/level.png"/>27 - <img src="/style/images/many/silver.png"/>67600<br/>';
echo'<img src="/style/images/user/level.png"/>28 - <img src="/style/images/many/silver.png"/>72900<br/>';
echo'<img src="/style/images/user/level.png"/>29 - <img src="/style/images/many/silver.png"/>78400<br/>';
echo'<img src="/style/images/user/level.png"/>30 - <img src="/style/images/many/silver.png"/>84100<br/>';
echo'<img src="/style/images/user/level.png"/>31 - <img src="/style/images/many/gold.png"/>60<br/>';
echo'<img src="/style/images/user/level.png"/>32 - <img src="/style/images/many/silver.png"/>96100<br/>';
echo'<img src="/style/images/user/level.png"/>33 - <img src="/style/images/many/silver.png"/>102400<br/>';
echo'<img src="/style/images/user/level.png"/>34 - <img src="/style/images/many/silver.png"/>108900<br/>';
echo'<img src="/style/images/user/level.png"/>35 - <img src="/style/images/many/silver.png"/>115600<br/>';
echo'<img src="/style/images/user/level.png"/>36 - <img src="/style/images/many/silver.png"/>122500<br/>';
echo'<img src="/style/images/user/level.png"/>37 - <img src="/style/images/many/silver.png"/>129600<br/>';
echo'<img src="/style/images/user/level.png"/>38 - <img src="/style/images/many/silver.png"/>136900<br/>';
echo'<img src="/style/images/user/level.png"/>39 - <img src="/style/images/many/silver.png"/>144400<br/>';
echo'<img src="/style/images/user/level.png"/>40 - <img src="/style/images/many/silver.png"/>152100<br/>';
echo'<img src="/style/images/user/level.png"/>41 - <img src="/style/images/many/gold.png"/>80<br/>';
echo'<img src="/style/images/user/level.png"/>42 - <img src="/style/images/many/silver.png"/>168100<br/>';
echo'<img src="/style/images/user/level.png"/>43 - <img src="/style/images/many/silver.png"/>176400<br/>';
echo'<img src="/style/images/user/level.png"/>44 - <img src="/style/images/many/silver.png"/>184900<br/>';
echo'<img src="/style/images/user/level.png"/>45 - <img src="/style/images/many/silver.png"/>193600<br/>';
echo'<img src="/style/images/user/level.png"/>46 - <img src="/style/images/many/silver.png"/>202500<br/>';
echo'<img src="/style/images/user/level.png"/>47 - <img src="/style/images/many/silver.png"/>211600<br/>';
echo'<img src="/style/images/user/level.png"/>48 - <img src="/style/images/many/silver.png"/>220900<br/>';
echo'<img src="/style/images/user/level.png"/>49 - <img src="/style/images/many/silver.png"/>230400<br/>';
echo'<img src="/style/images/user/level.png"/>50 - <img src="/style/images/many/silver.png"/>240100<br/>';
echo'<img src="/style/images/user/level.png"/>51 - <img src="/style/images/many/gold.png"/>100<br/>';
echo'<img src="/style/images/user/level.png"/>52 - <img src="/style/images/many/silver.png"/>260100<br/>';
echo'<img src="/style/images/user/level.png"/>53 - <img src="/style/images/many/silver.png"/>270400<br/>';
echo'<img src="/style/images/user/level.png"/>54 - <img src="/style/images/many/silver.png"/>280900<br/>';
echo'<img src="/style/images/user/level.png"/>55 - <img src="/style/images/many/silver.png"/>291600<br/>';
echo'<img src="/style/images/user/level.png"/>56 - <img src="/style/images/many/silver.png"/>302500<br/>';
echo'<img src="/style/images/user/level.png"/>57 - <img src="/style/images/many/silver.png"/>313600<br/>';
echo'<img src="/style/images/user/level.png"/>58 - <img src="/style/images/many/silver.png"/>324900<br/>';
echo'<img src="/style/images/user/level.png"/>59 - <img src="/style/images/many/silver.png"/>336400<br/>';
echo'<img src="/style/images/user/level.png"/>60 - <img src="/style/images/many/silver.png"/>348100<br/>';
echo'<img src="/style/images/user/level.png"/>61 - <img src="/style/images/many/gold.png"/>120<br/>';
echo'<img src="/style/images/user/level.png"/>62 - <img src="/style/images/many/silver.png"/>372100<br/>';
echo'<img src="/style/images/user/level.png"/>63 - <img src="/style/images/many/silver.png"/>384400<br/>';
echo'<img src="/style/images/user/level.png"/>64 - <img src="/style/images/many/silver.png"/>396900<br/>';
echo'<img src="/style/images/user/level.png"/>65 - <img src="/style/images/many/silver.png"/>409600<br/>';
echo'<img src="/style/images/user/level.png"/>66 - <img src="/style/images/many/silver.png"/>422500<br/>';
echo'<img src="/style/images/user/level.png"/>67 - <img src="/style/images/many/silver.png"/>435600<br/>';
echo'<img src="/style/images/user/level.png"/>68 - <img src="/style/images/many/silver.png"/>448900<br/>';
echo'<img src="/style/images/user/level.png"/>69 - <img src="/style/images/many/silver.png"/>462400<br/>';
echo'<img src="/style/images/user/level.png"/>70 - <img src="/style/images/many/silver.png"/>476100<br/>';
echo'<img src="/style/images/user/level.png"/>71 - <img src="/style/images/many/gold.png"/>140<br/>';
echo'<img src="/style/images/user/level.png"/>72 - <img src="/style/images/many/silver.png"/>504100<br/>';
echo'<img src="/style/images/user/level.png"/>73 - <img src="/style/images/many/silver.png"/>518400<br/>';
echo'<img src="/style/images/user/level.png"/>74 - <img src="/style/images/many/silver.png"/>532900<br/>';
echo'<img src="/style/images/user/level.png"/>75 - <img src="/style/images/many/silver.png"/>547600<br/>';
echo'<img src="/style/images/user/level.png"/>76 - <img src="/style/images/many/silver.png"/>562500<br/>';
echo'<img src="/style/images/user/level.png"/>77 - <img src="/style/images/many/silver.png"/>577600<br/>';
echo'<img src="/style/images/user/level.png"/>78 - <img src="/style/images/many/silver.png"/>592900<br/>';
echo'<img src="/style/images/user/level.png"/>79 - <img src="/style/images/many/silver.png"/>608400<br/>';
echo'<img src="/style/images/user/level.png"/>80 - <img src="/style/images/many/silver.png"/>624100<br/>';
echo'<img src="/style/images/user/level.png"/>81 - <img src="/style/images/many/gold.png"/>160<br/>';
echo'<img src="/style/images/user/level.png"/>82 - <img src="/style/images/many/silver.png"/>656100<br/>';
echo'<img src="/style/images/user/level.png"/>83 - <img src="/style/images/many/silver.png"/>672400<br/>';
echo'<img src="/style/images/user/level.png"/>84 - <img src="/style/images/many/silver.png"/>688900<br/>';
echo'<img src="/style/images/user/level.png"/>85 - <img src="/style/images/many/silver.png"/>705600<br/>';
echo'<img src="/style/images/user/level.png"/>86 - <img src="/style/images/many/silver.png"/>722500<br/>';
echo'<img src="/style/images/user/level.png"/>87 - <img src="/style/images/many/silver.png"/>739600<br/>';
echo'<img src="/style/images/user/level.png"/>88 - <img src="/style/images/many/silver.png"/>756900<br/>';
echo'<img src="/style/images/user/level.png"/>89 - <img src="/style/images/many/silver.png"/>774400<br/>';
echo'<img src="/style/images/user/level.png"/>90 - <img src="/style/images/many/silver.png"/>792100<br/>';
echo'<img src="/style/images/user/level.png"/>91 - <img src="/style/images/many/gold.png"/>180<br/>';
echo'<img src="/style/images/user/level.png"/>92 - <img src="/style/images/many/silver.png"/>828100<br/>';
echo'<img src="/style/images/user/level.png"/>93 - <img src="/style/images/many/silver.png"/>846400<br/>';
echo'<img src="/style/images/user/level.png"/>94 - <img src="/style/images/many/silver.png"/>864900<br/>';
echo'<img src="/style/images/user/level.png"/>95 - <img src="/style/images/many/silver.png"/>883600<br/>';
echo'<img src="/style/images/user/level.png"/>96 - <img src="/style/images/many/silver.png"/>902500<br/>';
echo'<img src="/style/images/user/level.png"/>97 - <img src="/style/images/many/silver.png"/>921600<br/>';
echo'<img src="/style/images/user/level.png"/>98 - <img src="/style/images/many/silver.png"/>940900<br/>';
echo'<img src="/style/images/user/level.png"/>99 - <img src="/style/images/many/silver.png"/>960400<br/>';
echo'<img src="/style/images/user/level.png"/>100 - <img src="/style/images/many/silver.png"/>980100<br/>';
echo'<img src="/style/images/user/level.png"/>101 - <img src="/style/images/many/gold.png"/>2000<br/>';
echo'<img src="/style/images/user/level.png"/>102 - <img src="/style/images/many/silver.png"/>1020100<br/>';
echo'<img src="/style/images/user/level.png"/>103 - <img src="/style/images/many/silver.png"/>1040400<br/>';
echo'<img src="/style/images/user/level.png"/>104 - <img src="/style/images/many/silver.png"/>1060900<br/>';
echo'<img src="/style/images/user/level.png"/>105 - <img src="/style/images/many/silver.png"/>1081600<br/>';
echo'<img src="/style/images/user/level.png"/>106 - <img src="/style/images/many/silver.png"/>1102500<br/>';
echo'<img src="/style/images/user/level.png"/>107 - <img src="/style/images/many/silver.png"/>1123600<br/>';
echo'<img src="/style/images/user/level.png"/>108 - <img src="/style/images/many/silver.png"/>1144900<br/>';
echo'<img src="/style/images/user/level.png"/>109 - <img src="/style/images/many/silver.png"/>1166400<br/>';
echo'<img src="/style/images/user/level.png"/>110 - <img src="/style/images/many/silver.png"/>1188100<br/>';
echo'<img src="/style/images/user/level.png"/>111 - <img src="/style/images/many/gold.png"/>2200<br/>';
echo'<img src="/style/images/user/level.png"/>112 - <img src="/style/images/many/silver.png"/>1232100<br/>';
echo'<img src="/style/images/user/level.png"/>113 - <img src="/style/images/many/silver.png"/>1254400<br/>';
echo'<img src="/style/images/user/level.png"/>114 - <img src="/style/images/many/silver.png"/>1276900<br/>';
echo'<img src="/style/images/user/level.png"/>115 - <img src="/style/images/many/silver.png"/>1299600<br/>';
echo'<img src="/style/images/user/level.png"/>116 - <img src="/style/images/many/silver.png"/>1322500<br/>';
echo'<img src="/style/images/user/level.png"/>117 - <img src="/style/images/many/silver.png"/>1345600<br/>';
echo'<img src="/style/images/user/level.png"/>118 - <img src="/style/images/many/silver.png"/>1368900<br/>';
echo'<img src="/style/images/user/level.png"/>119 - <img src="/style/images/many/silver.png"/>1392400<br/>';
echo'<img src="/style/images/user/level.png"/>120 - <img src="/style/images/many/silver.png"/>1416100<br/>';
echo'<img src="/style/images/user/level.png"/>121 - <img src="/style/images/many/gold.png"/>2400<br/>';
echo'<img src="/style/images/user/level.png"/>122 - <img src="/style/images/many/silver.png"/>1464100<br/>';
echo'<img src="/style/images/user/level.png"/>123 - <img src="/style/images/many/silver.png"/>1488400<br/>';
echo'<img src="/style/images/user/level.png"/>124 - <img src="/style/images/many/silver.png"/>1512900<br/>';
echo'<img src="/style/images/user/level.png"/>125 - <img src="/style/images/many/silver.png"/>1537600<br/>';
echo'<img src="/style/images/user/level.png"/>126 - <img src="/style/images/many/silver.png"/>1562500<br/>';
echo'<img src="/style/images/user/level.png"/>127 - <img src="/style/images/many/silver.png"/>1587600<br/>';
echo'<img src="/style/images/user/level.png"/>128 - <img src="/style/images/many/silver.png"/>1612900<br/>';
echo'<img src="/style/images/user/level.png"/>129 - <img src="/style/images/many/silver.png"/>1638400<br/>';
echo'<img src="/style/images/user/level.png"/>130 - <img src="/style/images/many/silver.png"/>1664100<br/>';
echo'<img src="/style/images/user/level.png"/>131 - <img src="/style/images/many/gold.png"/>2600<br/>';
echo'<img src="/style/images/user/level.png"/>132 - <img src="/style/images/many/silver.png"/>1716100<br/>';
echo'<img src="/style/images/user/level.png"/>133 - <img src="/style/images/many/silver.png"/>1742400<br/>';
echo'<img src="/style/images/user/level.png"/>134 - <img src="/style/images/many/silver.png"/>1768900<br/>';
echo'<img src="/style/images/user/level.png"/>135 - <img src="/style/images/many/silver.png"/>1795600<br/>';
echo'<img src="/style/images/user/level.png"/>136 - <img src="/style/images/many/silver.png"/>1822500<br/>';
echo'<img src="/style/images/user/level.png"/>137 - <img src="/style/images/many/silver.png"/>1849600<br/>';
echo'<img src="/style/images/user/level.png"/>138 - <img src="/style/images/many/silver.png"/>1876900<br/>';
echo'<img src="/style/images/user/level.png"/>139 - <img src="/style/images/many/silver.png"/>1904400<br/>';
echo'<img src="/style/images/user/level.png"/>140 - <img src="/style/images/many/silver.png"/>1932100<br/>';
echo'<img src="/style/images/user/level.png"/>141 - <img src="/style/images/many/gold.png"/>2800<br/>';
echo'<img src="/style/images/user/level.png"/>142 - <img src="/style/images/many/silver.png"/>1988100<br/>';
echo'<img src="/style/images/user/level.png"/>143 - <img src="/style/images/many/silver.png"/>2016400<br/>';
echo'<img src="/style/images/user/level.png"/>144 - <img src="/style/images/many/silver.png"/>2044900<br/>';
echo'<img src="/style/images/user/level.png"/>145 - <img src="/style/images/many/silver.png"/>2073600<br/>';
echo'<img src="/style/images/user/level.png"/>146 - <img src="/style/images/many/silver.png"/>2102500<br/>';
echo'<img src="/style/images/user/level.png"/>147 - <img src="/style/images/many/silver.png"/>2131600<br/>';
echo'<img src="/style/images/user/level.png"/>148 - <img src="/style/images/many/silver.png"/>2160900<br/>';
echo'<img src="/style/images/user/level.png"/>149 - <img src="/style/images/many/silver.png"/>2190400<br/>';
echo'<img src="/style/images/user/level.png"/>150 - <img src="/style/images/many/silver.png"/>2220100<br/>';
echo'<img src="/style/images/user/level.png"/>151 - <img src="/style/images/many/gold.png"/>3000<br/>';
echo'<img src="/style/images/user/level.png"/>152 - <img src="/style/images/many/silver.png"/>2280100<br/>';
echo'<img src="/style/images/user/level.png"/>153 - <img src="/style/images/many/silver.png"/>2310400<br/>';
echo'<img src="/style/images/user/level.png"/>154 - <img src="/style/images/many/silver.png"/>2340900<br/>';
echo'<img src="/style/images/user/level.png"/>155 - <img src="/style/images/many/silver.png"/>2371600<br/>';
echo'<img src="/style/images/user/level.png"/>156 - <img src="/style/images/many/silver.png"/>2402500<br/>';
echo'<img src="/style/images/user/level.png"/>157 - <img src="/style/images/many/silver.png"/>2433600<br/>';
echo'<img src="/style/images/user/level.png"/>158 - <img src="/style/images/many/silver.png"/>2464900<br/>';
echo'<img src="/style/images/user/level.png"/>159 - <img src="/style/images/many/silver.png"/>2496400<br/>';
echo'<img src="/style/images/user/level.png"/>160 - <img src="/style/images/many/silver.png"/>2528100<br/>';
echo'<img src="/style/images/user/level.png"/>161 - <img src="/style/images/many/gold.png"/>3200<br/>';
echo'<img src="/style/images/user/level.png"/>162 - <img src="/style/images/many/silver.png"/>2592100<br/>';
echo'<img src="/style/images/user/level.png"/>163 - <img src="/style/images/many/silver.png"/>2624400<br/>';
echo'<img src="/style/images/user/level.png"/>164 - <img src="/style/images/many/silver.png"/>2656900<br/>';
echo'<img src="/style/images/user/level.png"/>165 - <img src="/style/images/many/silver.png"/>2689600<br/>';
echo'<img src="/style/images/user/level.png"/>166 - <img src="/style/images/many/silver.png"/>2722500<br/>';
echo'<img src="/style/images/user/level.png"/>167 - <img src="/style/images/many/silver.png"/>2755600<br/>';
echo'<img src="/style/images/user/level.png"/>168 - <img src="/style/images/many/silver.png"/>2788900<br/>';
echo'<img src="/style/images/user/level.png"/>169 - <img src="/style/images/many/silver.png"/>2822400<br/>';
echo'<img src="/style/images/user/level.png"/>170 - <img src="/style/images/many/silver.png"/>2856100<br/>';
echo'<img src="/style/images/user/level.png"/>171 - <img src="/style/images/many/gold.png"/>3400<br/>';
echo'<img src="/style/images/user/level.png"/>172 - <img src="/style/images/many/silver.png"/>2924100<br/>';
echo'<img src="/style/images/user/level.png"/>173 - <img src="/style/images/many/silver.png"/>2958400<br/>';
echo'<img src="/style/images/user/level.png"/>174 - <img src="/style/images/many/silver.png"/>2992900<br/>';
echo'<img src="/style/images/user/level.png"/>175 - <img src="/style/images/many/silver.png"/>3027600<br/>';
echo'<img src="/style/images/user/level.png"/>176 - <img src="/style/images/many/silver.png"/>3062500<br/>';
echo'<img src="/style/images/user/level.png"/>177 - <img src="/style/images/many/silver.png"/>3097600<br/>';
echo'<img src="/style/images/user/level.png"/>178 - <img src="/style/images/many/silver.png"/>3132900<br/>';
echo'<img src="/style/images/user/level.png"/>179 - <img src="/style/images/many/silver.png"/>3168400<br/>';
echo'<img src="/style/images/user/level.png"/>180 - <img src="/style/images/many/silver.png"/>3204100<br/>';
echo'<img src="/style/images/user/level.png"/>181 - <img src="/style/images/many/gold.png"/>3600<br/>';
echo'<img src="/style/images/user/level.png"/>182 - <img src="/style/images/many/silver.png"/>3276100<br/>';
echo'<img src="/style/images/user/level.png"/>183 - <img src="/style/images/many/silver.png"/>3312400<br/>';
echo'<img src="/style/images/user/level.png"/>184 - <img src="/style/images/many/silver.png"/>3348900<br/>';
echo'<img src="/style/images/user/level.png"/>185 - <img src="/style/images/many/silver.png"/>3385600<br/>';
echo'<img src="/style/images/user/level.png"/>186 - <img src="/style/images/many/silver.png"/>3422500<br/>';
echo'<img src="/style/images/user/level.png"/>187 - <img src="/style/images/many/silver.png"/>3459600<br/>';
echo'<img src="/style/images/user/level.png"/>188 - <img src="/style/images/many/silver.png"/>3496900<br/>';
echo'<img src="/style/images/user/level.png"/>189 - <img src="/style/images/many/silver.png"/>3534400<br/>';
echo'<img src="/style/images/user/level.png"/>190 - <img src="/style/images/many/silver.png"/>3572100<br/>';
echo'<img src="/style/images/user/level.png"/>191 - <img src="/style/images/many/gold.png"/>3800<br/>';
echo'<img src="/style/images/user/level.png"/>192 - <img src="/style/images/many/silver.png"/>3648100<br/>';
echo'<img src="/style/images/user/level.png"/>193 - <img src="/style/images/many/silver.png"/>3686400<br/>';
echo'<img src="/style/images/user/level.png"/>194 - <img src="/style/images/many/silver.png"/>3724900<br/>';
echo'<img src="/style/images/user/level.png"/>195 - <img src="/style/images/many/silver.png"/>3763600<br/>';
echo'<img src="/style/images/user/level.png"/>196 - <img src="/style/images/many/silver.png"/>3802500<br/>';
echo'<img src="/style/images/user/level.png"/>197 - <img src="/style/images/many/silver.png"/>3841600<br/>';
echo'<img src="/style/images/user/level.png"/>198 - <img src="/style/images/many/silver.png"/>3880900<br/>';
echo'<img src="/style/images/user/level.png"/>199 - <img src="/style/images/many/silver.png"/>3920400<br/>';
echo'<img src="/style/images/user/level.png"/>200 - <img src="/style/images/many/silver.png"/>3960100<br/>';
echo'<div style="padding: 2px;"></div>';
echo'<img src="/style/images/body/imp.png" alt=""/> <span style="font-size:14px; color:#dc50ff;">Каждый <img src="/style/images/user/level.png" alt=""/>10 ур. прокачиваеться за <img src="/style/images/many/gold.png" alt=""/>Золото </span><br/>';
echo'</span>';
echo'</div>';
echo'</div>';
}

#-Достижения-#
echo'<div class="line_1"></div>';
echo'<li><a href="/knowledge_basa?sort=user&spr=achive"><img src="/style/images/body/achive.png" alt=""/> Достижения</a></li>';
if($_GET['spr'] == 'achive'){
echo'<div class="line_1_m"></div>';
echo'<div class="page">';
echo'<div style="padding: 5px;">';
echo'<span class="whit">';
echo'<img src="/style/images/body/achive.png" alt=""/><span class="yellow">Достижения</span> - выполняя достижения вы получите неплохую <img src="/style/images/body/gift.png" alt="Подарок"/>Награду.<br/>';
echo'<img src="/style/images/body/achive.png" alt=""/><span class="yellow">Достижения 1 ранга:</span><br/>';
echo'<img src="/style/images/body/ok.png" alt=""/>Незнакомец: Сохранить своего игрока<br/>';
echo'<img src="/style/images/body/ohota.png" alt=""/>Охотник: Провести в охоте всего 14\'000 боев.<br/>';
echo'<img src="/style/images/body/league.png" alt=""/>Дуэлянт: Победить в дуэлях всего 5\'000 раз.<br/>';
echo'<img src="/style/images/body/bos.png" alt=""/>Уничтожитель: Победить боссов всего 5\'975 раз.<br/>';
echo'<img src="/style/images/body/daily_tasks.png" alt=""/>Исполнитель: Выполнить всего 1000 ежедневных заданий.<br/>';

echo'<img src="/style/images/body/achive.png" alt=""/><span class="yellow">Достижения 2 ранга:</span><br/>';
echo'<img src="/style/images/body/zamki.png" alt=""/>Защитник: Победить в замках всего 500 раз.<br/>';
echo'<img src="/style/images/body/reid.png" alt=""/>Рейдовик: Победить в рейде всего 400 раз.<br/>';
echo'<img src="/style/images/body/chest.png" alt=""/>Добытчик: Открыть всего 1\'000 сундуков.<br/>';
echo'<img src="/style/images/body/clan.png" alt=""/>Укрепленный: Вступить в клан.<br/>';

echo'<img src="/style/images/body/achive.png" alt=""/><span class="yellow">Достижения 3 ранга:</span><br/>';
echo'<img src="/style/images/body/level.png" alt=""/>Прокачанный: Получить всего 100 уровень.<br/>';
echo'<img src="/style/images/user/sila.png" alt=""/>Сильнейший: Прокачать силу всего до 200 уровня.<br/>';
echo'<img src="/style/images/user/zashita.png" alt=""/>Защищенный: Прокачать защиту всего до 200 уровня.<br/>';
echo'<img src="/style/images/user/health.png" alt=""/>Живучий: Прокачать здоровье всего до 200 уровня.<br/>';

echo'<img src="/style/images/body/imp.png" alt=""/> <span style="font-size:14px; color:#dc50ff;">За выполнения достижений каждого ранга вы получите уникальный комплект.</span><br/>';
echo'</div>';
echo'</div>';
}

#-Черный список-#
echo'<div class="line_1"></div>';
echo'<li><a href="/knowledge_basa?sort=user&spr=ignor_list"><img src="/style/images/body/error.png" alt=""/> Чёрный список</a></li>';
if($_GET['spr'] == 'ignor_list'){
echo'<div class="line_1_m"></div>';
echo'<div class="page">';
echo'<div style="padding: 5px;">';
echo'<span class="whit">';
echo'<img src="/style/images/body/error.png" alt=""/><span class="yellow">Чёрный список</span> - игроки которых вы добавили в этот список, не смогут писать вам личные сообщения.';
echo'</div>';
echo'</div>';
}

#-Реферальная программа-#
echo'<div class="line_1"></div>';
echo'<li><a href="/knowledge_basa?sort=user&spr=ref"><img src="/style/images/many/gold.png" alt=""/> Реферальная программа</a></li>';
if($_GET['spr'] == 'ref'){
echo'<div class="line_1_m"></div>';
echo'<div class="page">';
echo'<div style="padding: 5px;">';
echo'<span class="whit">';
echo'<img src="/style/images/many/gold.png" alt=""/><span class="yellow">Реферальная программа</span> - приглашайте новых игроков в игру и если они купят <span class="gray">Золото</span> вы получите 15% от суммы покупки.';
echo'</div>';
echo'</div>';
}

#-Подарки-#
echo'<div class="line_1"></div>';
echo'<li><a href="/knowledge_basa?sort=user&spr=gift_user"><img src="/style/images/body/gift.png" alt=""/> Подарки</a></li>';
if($_GET['spr'] == 'gift_user'){
echo'<div class="line_1_m"></div>';
echo'<div class="page">';
echo'<div style="padding: 5px;">';
echo'<span class="whit">';
echo'<img src="/style/images/body/gift.png" alt=""/><span class="yellow">Подарки</span> - дарите друг другу подарки на праздники и просто так, чтобы порадовать друг друга.<br/>';
echo'<img src="/style/images/body/imp.png" alt=""/><span style="font-size:14px; color:#dc50ff;"> Доступны с <img src="/style/images/user/level.png" alt=""/>10 ур.</span><br/>';
echo'<img src="/style/images/body/imp.png" alt=""/><span style="font-size:14px; color:#dc50ff;"> Если вам прислали подарок который нарушает правила игры вы можете его удалить</span><br/>';
echo'</div>';
echo'</div>';
}

echo'<div class="line_1"></div>';
echo'<li><a href="/knowledge_basa"><img src="/style/images/body/back.png" alt=""/> Назад</a></li>';
echo'</div>';
echo'</div>';
?>